# ── Project Metadata ──────────────────────────────────
project:
  title: Aral Sea Level Modelling
  type: MSc Thesis
  institution: TU Delft
  Author: A.B. van der Veen
  version: "0.1"
  date: 2024-06-01
  description: all the configuration parameters for the Aral Sea level modelling project, including paths, model parameters, experiments, plotting settings, and station information.


# ── Paths ─────────────────────────────────────────────
paths:
  project_root:  "/home/avandervee3/aral_sea_full_project"

  #data directories
  data_dir:      ./data
  clonemaps_dir: ./data/clonemaps
  grdc_dir:      ./data/grdc
  shapefiles_dir: ./data/shapefiles
  forcing_dir:   ./data/forcing

  #configuration directories
  config_dir:    ./config

  #output directories
  output_dir:    ./outputs

  #notebooks and scripts directories
  notebooks_dir: ./notebooks
  scripts_dir:   ./scripts



# -- Meteorological Forcing Data --
forcing:
  basin: "AralSea_basin"

  models: ["MIROC6", "NorESM2-LM", "CanESM5", "FGOALS-g3", "MPI-ESM1-2-HR", "MRI-ESM2-0"]
  ensemble: ["r1i1p1f1"]
  scenarios: ["ssp126", "ssp245", "ssp370", "ssp585"]
  ewatercycle_tail: "work/diagnostic/script"




simulation_period:
  historical_cmip_start_date: "1940-01-01T00:00:00Z"
  historical_cmip_end_date: "2014-12-31T00:00:00Z"
  future_start_date: "2015-01-01T00:00:00Z"
  future_end_date: "2100-12-31T00:00:00Z"
  era5_start_date: "1940-01-01T00:00:00Z"
  era5_end_date: "2020-12-31T00:00:00Z"





# -- Model Parameters --

